### PR TITLE
Add closing tag to RegExp

### PR DESCRIPTION
**Pull request by gleidsonh**
Return true to closing tag, not only opening tags

### CODE REVIEW

**Comment by sindresorhus** [comment]
Just a closing tag is not valid HTML.

**Comment by gleidsonh** [comment]
> Just a closing tag is not valid HTML.

Not even an opening tag is valid HTML. Furthermore, I thought that this library was not meant to [validate HTML](https://github.com/sindresorhus/is-html/issues/9), but rather to inform whether it is an HTML tag or not.

**Comment by sindresorhus** [comment]
Many elements only need an opening tag and the browser will fix it.

This is totally valid:

```html
<p>abc
```

However, just an ending tag is not valid.

This is not about validating HTML, but maybe you could elaborate on what problem your change will resolve?

**Comment by gleidsonh** [comment]
I thought this functionality was necessary to solve my problem, however I found a better way. Anyway, as I said, I consider it a valid html tag (since there is an opening tag and a closing tag). Just as a browser fixes `<p>abc`, it also fixes `abc</p>,` just not as "valid HTML".

It is at your disposal to accept or not this PR. Anyway, if someone else needs this functionality, just clone the project and add it manually, perhaps with an even more appropriate name: is-html-tag. Fortunately the way I found it doesn't need that anymore.

Thanks for the help and your time.

**Pull request closed without merging**
